name : NASA Prject CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20.11.1
        uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
    - run: npm install
    - run: npm run build --prefix client